version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-home-api
    volumes:
      - .:/app # <--- hot reload fungerar här
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=home/sensors/#
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: smart-home-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" # websockets utåt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
